[package]
name = "blockind"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
subxt = { version = "0.37" }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
